### ISSUE TITLE
ros-kinetic-catkin-virtualenv dependency issue

### ISSUE THREAD

**Issue by Affonso-Gui** [locusrobotics/catkin_virtualenv#74]
Hello, 

I just started having some dependency issues on kinetic with the 0.6.1 release, as it requires `catkin-pkg==0.4.20`, but the default apt version is `0.4.22`

```
$ apt-cache policy python-catkin-pkg
python-catkin-pkg:
  Installed: 0.4.22-100
  Candidate: 0.4.22-100
  Version table:
 *** 0.4.22-100 500
        500 http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
        500 http://packages.ros.org/ros/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
     0.2.10-2 500
        500 http://jp.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://jp.archive.ubuntu.com/ubuntu xenial/universe i386 Packages
```

Seems to be working fine when I manually bump the requirements.txt to 0.4.22.

The error I got:
```
ERROR: Could not find a version that satisfies the requirement catkin-pkg==0.4.20 (from -r /opt/ros/kinetic/share/catkin_virtualenv/requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for catkin-pkg==0.4.20 (from -r /opt/ros/kinetic/share/catkin_virtualenv/requirements.txt (line 1))
```

Also, had no problems when testing with melodic, as ros-melodic-catkin-virtualenv still resolves to version 0.5.2

**Comment by paulbovbel** [comment]
Thanks for the report. Generally the version in apt doesn't matter, since 0.4.20 is what pip pulls into the virtualenv from https://pypi.org/project/catkin-pkg/

https://github.com/locusrobotics/catkin_virtualenv/blob/master/catkin_virtualenv/requirements.txt pins some specific versions of those dependencies, whatever was available at the time, and they can certainly be advanced if necessary. But we use this package extensively in xenial, and 0.4.20 seems to be installable

@gavanderhoorn have you noticed any issues?

**Comment by gavanderhoorn** [comment]
No, I've not seen this (yet).

**Comment by Affonso-Gui** [comment]
When trying to recreate the error on docker it seemed to be working just fine, so the odds are that it was just something wrong with my pc's env/ installation? (I was struggling with pip versions and python2vs3 compability, which may have caused it)

Anyways I'm closing this for now as I am not being able to reach the error.  Thanks for your help, and will get back if I can find some more details on it!
